import { useState } from "react";
import { useAuth } from "@/hooks/use-auth";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { BarChart3, Download, Users, Clock, TrendingUp, Percent } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, PieChart, Pie, Cell, Legend } from "recharts";

const BASE = import.meta.env.BASE_URL.replace(/\/$/, "");
const COLORS = ["#2563eb", "#10b981", "#f59e0b", "#ef4444", "#8b5cf6"];

export default function Reports() {
  const { user } = useAuth();
  const [period, setPeriod] = useState("weekly");

  const { data, isLoading } = useQuery({
    queryKey: ["/api/reports", user?.orgId, period],
    queryFn: async () => {
      const res = await fetch(`${BASE}/api/organizations/${user?.orgId}/reports/visitor-traffic?period=${period}`, { credentials: "include" });
      if (!res.ok) throw new Error("Failed");
      return res.json();
    },
    enabled: !!user?.orgId,
  });

  const handleExportPDF = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    const reportData = data?.data || [];
    const summary = data?.summary || {};

    const tableRows = reportData.map((d: any) =>
      `<tr>
        <td style="padding:8px;border-bottom:1px solid #e2e8f0">${d.label}</td>
        <td style="padding:8px;border-bottom:1px solid #e2e8f0;text-align:center">${d.totalVisitors}</td>
        <td style="padding:8px;border-bottom:1px solid #e2e8f0;text-align:center">${d.checkedIn}</td>
        <td style="padding:8px;border-bottom:1px solid #e2e8f0;text-align:center">${d.walkIns}</td>
        <td style="padding:8px;border-bottom:1px solid #e2e8f0;text-align:center">${d.preRegistered}</td>
      </tr>`
    ).join("");

    printWindow.document.write(`
      <!DOCTYPE html>
      <html><head><title>Visitor Traffic Report</title>
      <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1e293b; }
        h1 { font-size: 24px; margin-bottom: 4px; }
        .subtitle { color: #64748b; margin-bottom: 24px; }
        .stats { display: flex; gap: 16px; margin-bottom: 24px; }
        .stat-card { flex:1; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 16px; text-align: center; }
        .stat-value { font-size: 28px; font-weight: 700; }
        .stat-label { font-size: 12px; color: #64748b; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th { background: #f1f5f9; padding: 10px 8px; text-align: left; font-weight: 600; font-size: 13px; }
        .footer { margin-top: 32px; text-align: center; color: #94a3b8; font-size: 11px; }
      </style>
      </head><body>
        <h1>Visitor Traffic Report</h1>
        <p class="subtitle">Period: ${period} | Generated: ${new Date().toLocaleDateString()}</p>
        <div class="stats">
          <div class="stat-card"><div class="stat-value">${summary.totalVisitors || 0}</div><div class="stat-label">Total Visitors</div></div>
          <div class="stat-card"><div class="stat-value">${summary.approvalRate || 0}%</div><div class="stat-label">Approval Rate</div></div>
          <div class="stat-card"><div class="stat-value">${summary.peakHour || "—"}</div><div class="stat-label">Peak Hour</div></div>
        </div>
        <table>
          <thead><tr><th>Period</th><th style="text-align:center">Total</th><th style="text-align:center">Checked In</th><th style="text-align:center">Walk-ins</th><th style="text-align:center">Pre-registered</th></tr></thead>
          <tbody>${tableRows}</tbody>
        </table>
        <div class="footer">Generated by Availo Ventry — Powered by T2</div>
        <script>window.print();</script>
      </body></html>
    `);
    printWindow.document.close();
  };

  const reportData = data?.data || [];
  const summary = data?.summary || {};

  const totalWalkIns = reportData.reduce((a: number, d: any) => a + d.walkIns, 0);
  const totalPreReg = reportData.reduce((a: number, d: any) => a + d.preRegistered, 0);
  const pieData = [
    { name: "Walk-in", value: totalWalkIns },
    { name: "Pre-registered", value: totalPreReg },
  ].filter(d => d.value > 0);

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-display font-bold text-foreground">Reports</h1>
          <p className="text-muted-foreground mt-1">Visitor traffic analytics and insights.</p>
        </div>
        <div className="flex gap-3">
          <Select value={period} onValueChange={setPeriod}>
            <SelectTrigger className="w-36 rounded-xl"><SelectValue /></SelectTrigger>
            <SelectContent>
              <SelectItem value="daily">Daily</SelectItem>
              <SelectItem value="weekly">Weekly</SelectItem>
              <SelectItem value="monthly">Monthly</SelectItem>
            </SelectContent>
          </Select>
          <Button variant="outline" className="gap-2 rounded-xl" onClick={handleExportPDF}>
            <Download className="w-4 h-4" /> Export PDF
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
        {[
          { title: "Total Visitors", value: summary.totalVisitors || 0, icon: Users, color: "text-blue-600", bg: "bg-blue-100" },
          { title: "Approval Rate", value: `${summary.approvalRate || 0}%`, icon: Percent, color: "text-emerald-600", bg: "bg-emerald-100" },
          { title: "Peak Hour", value: summary.peakHour || "—", icon: Clock, color: "text-amber-600", bg: "bg-amber-100" },
          { title: "Avg Duration", value: `${summary.avgDuration || 0}m`, icon: TrendingUp, color: "text-indigo-600", bg: "bg-indigo-100" },
        ].map((s, i) => (
          <Card key={i} className="border-border/50 shadow-sm rounded-2xl">
            <CardContent className="p-5 flex items-center gap-3">
              <div className={`w-11 h-11 rounded-xl flex items-center justify-center ${s.bg} ${s.color}`}>
                <s.icon className="w-5 h-5" />
              </div>
              <div>
                <p className="text-xs text-muted-foreground font-medium">{s.title}</p>
                <p className="text-xl font-bold text-foreground">{s.value}</p>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card className="col-span-2 border-border/50 shadow-sm rounded-2xl">
          <CardHeader><CardTitle className="font-display">Visitor Traffic</CardTitle></CardHeader>
          <CardContent>
            {isLoading ? <div className="h-[300px] flex items-center justify-center text-muted-foreground">Loading...</div> : (
              <div className="h-[300px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={reportData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E2E8F0" />
                    <XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: "#64748B", fontSize: 12 }} />
                    <YAxis axisLine={false} tickLine={false} tick={{ fill: "#64748B" }} />
                    <Tooltip contentStyle={{ borderRadius: "12px", border: "none", boxShadow: "0 10px 15px -3px rgba(0,0,0,0.1)" }} />
                    <Bar dataKey="totalVisitors" name="Total" fill="#2563eb" radius={[4, 4, 0, 0]} maxBarSize={40} />
                    <Bar dataKey="checkedIn" name="Checked In" fill="#10b981" radius={[4, 4, 0, 0]} maxBarSize={40} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            )}
          </CardContent>
        </Card>

        <Card className="border-border/50 shadow-sm rounded-2xl">
          <CardHeader><CardTitle className="font-display">Visit Types</CardTitle></CardHeader>
          <CardContent>
            {pieData.length === 0 ? (
              <div className="h-[250px] flex items-center justify-center text-muted-foreground">No data</div>
            ) : (
              <div className="h-[250px]">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie data={pieData} cx="50%" cy="50%" innerRadius={50} outerRadius={80} dataKey="value" label>
                      {pieData.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}
                    </Pie>
                    <Legend />
                    <Tooltip />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
